#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"
#include "funcs.h"
#include "caesar.h"

// add your tests here

TEST_CASE("shiftChar"){
  CHECK(shiftChar('W', 5) == 'B');
  CHECK(shiftChar('o', 10) == 'y');
  CHECK(shiftChar('!', 15) == '!');
}

TEST_CASE("Caesar Encryption"){
  CHECK(encryptCaesar("Way to Go!", 5) == "Bfd yt Lt!");
  CHECK(encryptCaesar("Hello, World!", 10) == "Rovvy, Gybvn!");
  CHECK(encryptCaesar("Everybody loves cats!", 15) == "Tktgnqdsn adkth rpih!");
}

TEST_CASE("Solve Cipher Function"){
  CHECK(solve(encryptCaesar("What if a writer or novelist decided to write a 300-page book with no breaks in the text for new ideas, new chapters, or even character dialogue? It would be so overwhelming that the reader would probably take one look and close the book forever. When writing is divided up into manageable parts that are cohesive, it's much easier for the reader to take in and process. A paragraph is a distinct segment of writing, often includes more than one sentence, and is separated from other paragraphs and text by a space. Paragraphs break up text into manageable chunks that are easily read and visually make it more appealing and less daunting. The word paragraph comes from the Latin word paragraphos, which is roughly translated to mean a short-stroke marking a break in sense. The term graph is Latin for writing. There is often some confusion about what the difference is between a paragraph and an essay. The best way to understand the difference is to think of the essay as a bigger version of a paragraph. A paragraph is made up of a topic sentence, supporting sentences, and a concluding sentence. An essay has all the same parts; only instead of sentences, an essay is made up of paragraphs.", 10)) == "What if a writer or novelist decided to write a 300-page book with no breaks in the text for new ideas, new chapters, or even character dialogue? It would be so overwhelming that the reader would probably take one look and close the book forever. When writing is divided up into manageable parts that are cohesive, it's much easier for the reader to take in and process. A paragraph is a distinct segment of writing, often includes more than one sentence, and is separated from other paragraphs and text by a space. Paragraphs break up text into manageable chunks that are easily read and visually make it more appealing and less daunting. The word paragraph comes from the Latin word paragraphos, which is roughly translated to mean a short-stroke marking a break in sense. The term graph is Latin for writing. There is often some confusion about what the difference is between a paragraph and an essay. The best way to understand the difference is to think of the essay as a bigger version of a paragraph. A paragraph is made up of a topic sentence, supporting sentences, and a concluding sentence. An essay has all the same parts; only instead of sentences, an essay is made up of paragraphs.");
  
  CHECK(solve(encryptCaesar("It is important to note that a paragraph does not have a minimum or maximum number of sentences that it must have to fit the definition of a paragraph. Some writers will opt to use very short paragraphs, while others will include dozens of sentences in their paragraphs. It is also important to know that most writers separate lines of dialogue into paragraphs, so if a character only speaks a single line, it will be its own paragraph. Keeping that in mind, there is a general agreement on the format of a standard paragraph, which especially applies to informational and argumentative or persuasive writing. A paragraph should be divided into three distinct sections that each serve a purpose to the paragraph as a whole.", 5)) == "It is important to note that a paragraph does not have a minimum or maximum number of sentences that it must have to fit the definition of a paragraph. Some writers will opt to use very short paragraphs, while others will include dozens of sentences in their paragraphs. It is also important to know that most writers separate lines of dialogue into paragraphs, so if a character only speaks a single line, it will be its own paragraph. Keeping that in mind, there is a general agreement on the format of a standard paragraph, which especially applies to informational and argumentative or persuasive writing. A paragraph should be divided into three distinct sections that each serve a purpose to the paragraph as a whole.");

  CHECK(solve(encryptCaesar("When I was a little boy in elementary school, the neighborhood kids and I all looked forward to playing so many games in my backyard during the long summer holidays between grades. For instance, one of our favorite games was whiffle ball, a kid's version of baseball. All we needed was a cheap plastic bat and a cheap plastic ball and we could entertain ourselves in the backyard from morning to afternoon. Or if we broke the bat or lost the ball, we would play Red Rover, Red Rover. To play this game, we would join hands in two opposing lines and hurl ourselves at the locked wrists of the opposing team, trying to break through their line. Once the sun set, our favorite game was hide-and-seek. My backyard was perfect because there were lots of bushes and trees where we could hide out of sight of the kid who was it. Even on rainy days, we had fun activities out in the garden shed in the corner of the backyard. For instance, we would often act out our favorite TV game shows, like Lets Make a Deal, or sing along to the theme song from The Monkees, a popular TV show about a rock-and-roll band, on my little record player. Even now, fifty years later, I still look back on all those fun summertime games out in my backyard with a lot of fondness.", 15)) == "When I was a little boy in elementary school, the neighborhood kids and I all looked forward to playing so many games in my backyard during the long summer holidays between grades. For instance, one of our favorite games was whiffle ball, a kid's version of baseball. All we needed was a cheap plastic bat and a cheap plastic ball and we could entertain ourselves in the backyard from morning to afternoon. Or if we broke the bat or lost the ball, we would play Red Rover, Red Rover. To play this game, we would join hands in two opposing lines and hurl ourselves at the locked wrists of the opposing team, trying to break through their line. Once the sun set, our favorite game was hide-and-seek. My backyard was perfect because there were lots of bushes and trees where we could hide out of sight of the kid who was it. Even on rainy days, we had fun activities out in the garden shed in the corner of the backyard. For instance, we would often act out our favorite TV game shows, like Lets Make a Deal, or sing along to the theme song from The Monkees, a popular TV show about a rock-and-roll band, on my little record player. Even now, fifty years later, I still look back on all those fun summertime games out in my backyard with a lot of fondness.");
}

